### List all employees
GET http://localhost:8080/api/employees

### Create employee
POST http://localhost:8080/api/employees
Content-Type: application/json

{
    "name": "John Doe 105"
}

### Naplózás

GET http://localhost:8080/actuator/loggers/employees

### Módosítás

POST http://localhost:8080/actuator/loggers/employees
Content-Type: application/json

{
    "configuredLevel": "debug"
}
