apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: addresses
  name: addresses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addresses
  template:
    metadata:
      labels:
        app: addresses
    spec:
      containers:
      - image: training360/addresses
        name: addresses
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: addresses
  name: addresses
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: addresses
  type: ClusterIP
