apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eventstore
  name: eventstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventstore
  template:
    metadata:
      labels:
        app: eventstore
    spec:
      containers:
      - image: training360/eventstore
        name: eventstore
        env:
          - name: SPRING_ARTEMIS_BROKER-URL
            value: tcp://artemis:61616
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eventstore
  name: eventstore
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: eventstore
  type: ClusterIP
